version: '3.3'

services:
  stable-diffusion:
    container_name: sd
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env_docker
    volumes:
      - .:/sd
      - ./outputs:/sd/outputs
      - conda_env:/opt/conda
      - root_profile:/root
    ports:
      - '7860:7860'
    devices:
      - "/dev/kfd"
      - "/dev/dri"
    group_add:
      - "video"
    ipc: "host"
    cap_add:
      - "SYS_PTRACE"
    security_opt:
      - seccomp=unconfined

volumes:
  conda_env:
  root_profile:
